# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Unit Test
      run: go test -v --tags=unit ./...

    - name: Docker compose down
      run: docker-compose -f docker-compose.yml down

    - name: Docker compose up
      run: docker-compose -f docker-compose.yml up --build --abort-on-container-exit --exit-code-from integration_tests
